[Paths]
Prefix=../
Documentation=doc
Headers=include
Libraries=lib
LibraryExecutables=bin
Binaries=bin
Plugins=plugins
QmlImports=qml
ArchData=.
Data=.
Translations=translations
Examples=examples
Tests=tests
Settings=etc/xdg
HostPrefix=../../x64
HostBinaries=bin
HostLibraries=lib
HostLibraryExecutables=bin
HostData=../ARM64
Sysroot=
SysrootifyPrefix=false
TargetSpec=win32-arm64-msvc
HostSpec=
